In [1]:
import pandas as pd

dust = pd.read_csv("C:/Users/Dell5371/Downloads/dust.csv", encoding = 'cp949')
temp = pd.read_csv("C:/Users/Dell5371/Downloads/temp.csv", encoding = 'cp949')

In [2]:
dust.shape

(8248, 4)

In [3]:
temp.shape

(8736, 11)

In [4]:
dust.columns

Index(['지점', '지점명', '일시', '1시간평균 미세먼지농도(㎍/㎥)'], dtype='str')

In [5]:
temp.columns

Index(['지점', '지점명', '일시', '기온(°C)', '강수량(mm)', '풍속(m/s)', '풍향(16방위)', '습도(%)',
       '현지기압(hPa)', '전운량(10분위)', '중하층운량(10분위)'],
      dtype='str')

In [6]:
dust.isnull().sum()

지점                   0
지점명                  0
일시                   0
1시간평균 미세먼지농도(㎍/㎥)    0
dtype: int64

In [7]:
temp.isnull().sum()

지점                0
지점명               0
일시                0
기온(°C)            0
강수량(mm)        7662
풍속(m/s)           0
풍향(16방위)          0
습도(%)             0
현지기압(hPa)         0
전운량(10분위)         0
중하층운량(10분위)       0
dtype: int64

In [8]:
temp[temp['강수량(mm)'].isnull()]

,지점,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),전운량(10분위),중하층운량(10분위)
0,108,서울,2025-04-20 01:00,11.6,NaN,1.0,270,93,999.4,0,0
1,108,서울,2025-04-20 02:00,11.2,NaN,1.3,290,94,999.2,0,0
2,108,서울,2025-04-20 03:00,10.6,NaN,2.2,270,95,999.6,2,2
3,108,서울,2025-04-20 04:00,10.1,NaN,1.4,250,93,999.6,0,0
4,108,서울,2025-04-20 05:00,9.7,NaN,0.6,320,94,999.9,0,0
...,...,...,...,...,...,...,...,...,...,...,...
8731,108,서울,2026-04-18 20:00,21.3,NaN,3.1,250,48,1003.4,8,1
8732,108,서울,2026-04-18 21:00,20.1,NaN,2.4,250,52,1004.2,8,0
8733,108,서울,2026-04-18 22:00,19.2,NaN,2.8,250,55,1004.5,8,6
8734,108,서울,2026-04-18 23:00,18.5,NaN,2.5,250,58,1004.7,3,3
8735,108,서울,2026-04-19 00:00,17.7,NaN,1.4,250,58,1004.6,7,0

In [9]:
temp[temp['강수량(mm)'].notnull()]

,지점,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),전운량(10분위),중하층운량(10분위)
49,108,서울,2025-04-22 02:00,20.1,0.0,1.0,270,77,999.1,10,9
50,108,서울,2025-04-22 03:00,19.8,0.0,1.1,320,80,998.5,10,3
51,108,서울,2025-04-22 04:00,19.6,0.0,0.9,360,80,997.7,10,8
52,108,서울,2025-04-22 05:00,19.6,0.0,1.4,360,81,996.9,10,8
53,108,서울,2025-04-22 06:00,19.2,0.8,1.1,20,89,996.3,10,9
...,...,...,...,...,...,...,...,...,...,...,...
8529,108,서울,2026-04-10 10:00,10.2,0.4,2.8,230,96,990.8,10,10
8530,108,서울,2026-04-10 11:00,9.7,0.2,3.9,230,94,991.9,10,10
8531,108,서울,2026-04-10 12:00,9.6,0.1,3.2,200,95,992.3,10,10
8545,108,서울,2026-04-11 02:00,8.6,0.0,2.1,180,89,999.7,10,10
8546,108,서울,2026-04-11 03:00,8.4,0.0,2.6,230,89,1000.4,10,10

In [10]:
dust.dtypes

지점                   int64
지점명                    str
일시                     str
1시간평균 미세먼지농도(㎍/㎥)    int64
dtype: object

In [11]:
common_time = set(temp['일시']) & set(dust['일시'])
len(common_time)

8248

In [12]:
temp.dtypes

지점               int64
지점명                str
일시                 str
기온(°C)         float64
강수량(mm)        float64
풍속(m/s)        float64
풍향(16방위)         int64
습도(%)            int64
현지기압(hPa)      float64
전운량(10분위)        int64
중하층운량(10분위)      int64
dtype: object

In [13]:
dust['일시'] = pd.to_datetime(dust['일시'])
temp['일시'] = pd.to_datetime(temp['일시'])

In [14]:
dust.dtypes

지점                            int64
지점명                             str
일시                   datetime64[us]
1시간평균 미세먼지농도(㎍/㎥)             int64
dtype: object

In [15]:
temp.dtypes

지점                      int64
지점명                       str
일시             datetime64[us]
기온(°C)                float64
강수량(mm)               float64
풍속(m/s)               float64
풍향(16방위)                int64
습도(%)                   int64
현지기압(hPa)             float64
전운량(10분위)               int64
중하층운량(10분위)             int64
dtype: object

In [16]:
temp['강수량(mm)'] = temp['강수량(mm)'].fillna(0)

In [17]:
temp.isnull().sum()

지점             0
지점명            0
일시             0
기온(°C)         0
강수량(mm)        0
풍속(m/s)        0
풍향(16방위)       0
습도(%)          0
현지기압(hPa)      0
전운량(10분위)      0
중하층운량(10분위)    0
dtype: int64

In [18]:
common_df = pd.merge(temp, dust.drop(columns=['지점', '지점명']), on='일시')

common_df

,지점,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),전운량(10분위),중하층운량(10분위),1시간평균 미세먼지농도(㎍/㎥)
0,108,서울,2025-04-20 01:00:00,11.6,0.0,1.0,270,93,999.4,0,0,16
1,108,서울,2025-04-20 02:00:00,11.2,0.0,1.3,290,94,999.2,0,0,12
2,108,서울,2025-04-20 03:00:00,10.6,0.0,2.2,270,95,999.6,2,2,17
3,108,서울,2025-04-20 04:00:00,10.1,0.0,1.4,250,93,999.6,0,0,10
4,108,서울,2025-04-20 05:00:00,9.7,0.0,0.6,320,94,999.9,0,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...
8243,108,서울,2026-04-18 20:00:00,21.3,0.0,3.1,250,48,1003.4,8,1,59
8244,108,서울,2026-04-18 21:00:00,20.1,0.0,2.4,250,52,1004.2,8,0,44
8245,108,서울,2026-04-18 22:00:00,19.2,0.0,2.8,250,55,1004.5,8,6,49
8246,108,서울,2026-04-18 23:00:00,18.5,0.0,2.5,250,58,1004.7,3,3,44
8247,108,서울,2026-04-19 00:00:00,17.7,0.0,1.4,250,58,1004.6,7,0,41

In [19]:
common_df['일시'] = pd.to_datetime(common_df['일시'])

In [20]:
common_df['연도'] = common_df['일시'].dt.year
common_df['월'] = common_df['일시'].dt.month
common_df['일'] = common_df['일시'].dt.day
common_df['시각'] = common_df['일시'].dt.hour

In [21]:
common_df.head(30)

,지점,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),전운량(10분위),중하층운량(10분위),1시간평균 미세먼지농도(㎍/㎥),연도,월,일,시각
0,108,서울,2025-04-20 01:00:00,11.6,0.0,1.0,270,93,999.4,0,0,16,2025,4,20,1
1,108,서울,2025-04-20 02:00:00,11.2,0.0,1.3,290,94,999.2,0,0,12,2025,4,20,2
2,108,서울,2025-04-20 03:00:00,10.6,0.0,2.2,270,95,999.6,2,2,17,2025,4,20,3
3,108,서울,2025-04-20 04:00:00,10.1,0.0,1.4,250,93,999.6,0,0,10,2025,4,20,4
4,108,서울,2025-04-20 05:00:00,9.7,0.0,0.6,320,94,999.9,0,0,19,2025,4,20,5
5,108,서울,2025-04-20 06:00:00,9.5,0.0,0.7,70,94,1000.4,6,6,14,2025,4,20,6
6,108,서울,2025-04-20 07:00:00,10.2,0.0,0.8,270,96,1001.2,5,5,22,2025,4,20,7
7,108,서울,2025-04-20 08:00:00,11.4,0.0,2.0,270,95,1002.2,4,4,25,2025,4,20,8
8,108,서울,2025-04-20 09:00:00,12.9,0.0,2.1,250,89,1002.6,4,4,15,2025,4,20,9
9,108,서울,2025-04-20 10:00:00,15.8,0.0,1.4,110,77,1003.1,1,1,28,2025,4,20,10
10,108,서울,2025-04-20 11:00:00,17.9,0.0,2.9,50,67,1002.4,2,2,24,2025,4,20,11
11,108,서울,2025-04-20 12:00:00,19.3,0.0,2.1,70,59,1002.2,0,0,27,2025,4,20,12
12,108,서울,2025-04-20 13:00:00,21.2,0.0,2.6,160,55,1001.9,0,0,29,2025,4,20,13
13,108,서울,2025-04-20 14:00:00,22.5,0.0,1.7,230,53,1001.6,0,0,17,2025,4,20,14
14,108,서울,2025-04-20 15:00:00,23.4,0.0,2.1,230,50,1001.3,2,0,31,2025,4,20,15
15,108,서울,2025-04-20 16:00:00,23.7,0.0,2.2,230,48,1000.3,0,0,29,2025,4,20,16
16,108,서울,2025-04-20 17:00:00,24.0,0.0,2.0,290,47,1000.7,0,0,25,2025,4,20,17
17,108,서울,2025-04-20 18:00:00,23.4,0.0,2.3,250,47,1001.1,0,0,24,2025,4,20,18
18,108,서울,2025-04-20 19:00:00,21.7,0.0,2.0,320,47,1001.7,0,0,25,2025,4,20,19
19,108,서울,2025-04-20 20:00:00,19.7,0.0,1.9,270,57,1002.4,0,0,15,2025,4,20,20
20,108,서울,2025-04-20 21:00:00,18.7,0.0,1.4,270,57,1003.1,0,0,11,2025,4,20,21
21,108,서울,2025-04-20 22:00:00,17.7,0.0,1.3,290,61,1003.7,0,0,10,2025,4,20,22
22,108,서울,2025-04-20 23:00:00,16.7,0.0,1.1,250,65,1003.8,0,0,13,2025,4,20,23
23,108,서울,2025-04-21 00:00:00,15.9,0.0,0.6,180,69,1003.9,3,0,16,2025,4,21,0
24,108,서울,2025-04-21 01:00:00,15.3,0.0,1.3,50,70,1004.2,0,0,9,2025,4,21,1
25,108,서울,2025-04-21 02:00:00,14.7,0.0,2.7,70,74,1004.0,0,0,19,2025,4,21,2
26,108,서울,2025-04-21 03:00:00,14.5,0.0,2.0,70,76,1004.3,3,0,23,2025,4,21,3
27,108,서울,2025-04-21 04:00:00,14.4,0.0,1.9,70,78,1004.7,6,0,26,2025,4,21,4
28,108,서울,2025-04-21 05:00:00,14.3,0.0,2.4,50,80,1004.9,0,0,27,2025,4,21,5
29,108,서울,2025-04-21 06:00:00,14.3,0.0,2.6,70,83,1004.8,4,1,27,2025,4,21,6

In [22]:
def get_season(month):
    if month in [3, 4, 5]:
        return '봄'
    elif month in [6, 7, 8]:
        return '여름'
    elif month in [9, 10, 11]:
        return '가을'
    else:
        return '겨울'

common_df['계절'] = common_df['월'].apply(get_season)

In [23]:
common_df.shape

(8248, 17)

In [24]:
common_df.dtypes

지점                            int64
지점명                             str
일시                   datetime64[us]
기온(°C)                      float64
강수량(mm)                     float64
풍속(m/s)                     float64
풍향(16방위)                      int64
습도(%)                         int64
현지기압(hPa)                   float64
전운량(10분위)                     int64
중하층운량(10분위)                   int64
1시간평균 미세먼지농도(㎍/㎥)             int64
연도                            int32
월                             int32
일                             int32
시각                            int32
계절                              str
dtype: object

In [25]:
common_df

,지점,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),전운량(10분위),중하층운량(10분위),1시간평균 미세먼지농도(㎍/㎥),연도,월,일,시각,계절
0,108,서울,2025-04-20 01:00:00,11.6,0.0,1.0,270,93,999.4,0,0,16,2025,4,20,1,봄
1,108,서울,2025-04-20 02:00:00,11.2,0.0,1.3,290,94,999.2,0,0,12,2025,4,20,2,봄
2,108,서울,2025-04-20 03:00:00,10.6,0.0,2.2,270,95,999.6,2,2,17,2025,4,20,3,봄
3,108,서울,2025-04-20 04:00:00,10.1,0.0,1.4,250,93,999.6,0,0,10,2025,4,20,4,봄
4,108,서울,2025-04-20 05:00:00,9.7,0.0,0.6,320,94,999.9,0,0,19,2025,4,20,5,봄
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8243,108,서울,2026-04-18 20:00:00,21.3,0.0,3.1,250,48,1003.4,8,1,59,2026,4,18,20,봄
8244,108,서울,2026-04-18 21:00:00,20.1,0.0,2.4,250,52,1004.2,8,0,44,2026,4,18,21,봄
8245,108,서울,2026-04-18 22:00:00,19.2,0.0,2.8,250,55,1004.5,8,6,49,2026,4,18,22,봄
8246,108,서울,2026-04-18 23:00:00,18.5,0.0,2.5,250,58,1004.7,3,3,44,2026,4,18,23,봄
8247,108,서울,2026-04-19 00:00:00,17.7,0.0,1.4,250,58,1004.6,7,0,41,2026,4,19,0,봄

In [26]:
common_df.isnull().sum()

지점                   0
지점명                  0
일시                   0
기온(°C)               0
강수량(mm)              0
풍속(m/s)              0
풍향(16방위)             0
습도(%)                0
현지기압(hPa)            0
전운량(10분위)            0
중하층운량(10분위)          0
1시간평균 미세먼지농도(㎍/㎥)    0
연도                   0
월                    0
일                    0
시각                   0
계절                   0
dtype: int64

In [27]:
common_df.to_csv("C:/Users/Dell5371/Downloads/final_dataset.csv", encoding = 'cp949', index = False)